= Jactl vs Groovy [Java]
:toc: left
:sectnums:
:source-highlighter: rouge

// :source-highlighter: highlight.js
// :plantuml: http://localhost:8080/plantuml
// :plantuml-fetch-diagram: true
// :plantuml-size-limit: 8192
// :plantuml: plantuml.com/plantuml
// :diagram-server-url: https://kroki.io/
// :diagram-server-type: kroki_io

== Actions

=== Configuration

[%header,cols="1a,4a"]
|===
| id | value
| *description*
| Jactl vs Groovy [Java]
| *output_filename*
| benchmark_output.json
| *report_filename*
| benchmark_report.html
| *user_class*
| io.tulip.JactlUser
| *user_params*
|
[%header,cols="1a,3a"]
!===
! id ! value 
! *url* ! http://jsonplaceholder.typicode.com
! *httpVersion* ! HTTP_1_1
! *connectTimeoutMillis* ! 5000
! *readTimeoutMillis* ! 10000
! *shareConnections* ! True
! *debug* ! True
!===
| *user_actions*
|
[%header,cols="2a,2a,4a"]
!===
! id ! value ! description
! *1* ! Jactl:eval! 
! *2* ! Groovy:eval! 
! *3* ! Jython:eval! 
! *4* ! EvalEx:eval! 
!===
|===

== Contexts

=== Context-1

[%header,cols="1a,2a"]
|===
| id | value 
| *enabled* | True
| *num_users*   | 32
| *workload_model* | closed
|===

== Benchmarks

=== Jactl

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 2000.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! 100 
!===
| *warmup_duration1* | 30
| *warmup_duration2* | 30
| *benchmark_duration* | 30
| *benchmark_iterations* | 3
|===

=== Groovy

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 2000.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 2
! 100 
!===
| *warmup_duration1* | 30
| *warmup_duration2* | 30
| *benchmark_duration* | 30
| *benchmark_iterations* | 3
|===

=== Jython

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 2000.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 3
! 100 
!===
| *warmup_duration1* | 30
| *warmup_duration2* | 30
| *benchmark_duration* | 30
| *benchmark_iterations* | 3
|===

=== All

[%header,cols="1a,2a"]
|===
| id | value
| *enabled* | True
| *aps_rate* | 2000.0
| *scenario_actions* 
| 
[%header,cols="1a,2a"]
!===
! id ! weight 
! 1
! 34 
! 2
! 33 
! 3
! 33 
!===
| *warmup_duration1* | 30
| *warmup_duration2* | 10
| *benchmark_duration* | 30
| *benchmark_iterations* | 3
|===

== JSON Configuration File

[source,json,linenums]
----
{
    "actions": {
        "description": "Jactl vs Groovy [Java]", 
        "output_filename": "benchmark_output.json", 
        "report_filename": "benchmark_report.html", 
        "user_class": "io.tulip.JactlUser", 
        "user_params": {
            "url": "http://jsonplaceholder.typicode.com", 
            "httpVersion": "HTTP_1_1", 
            "connectTimeoutMillis": 5000, 
            "readTimeoutMillis": 10000, 
            "shareConnections": true, 
            "debug": true
        }, 
        "user_actions": {
            "1": "Jactl:eval", 
            "2": "Groovy:eval", 
            "3": "Jython:eval", 
            "4": "EvalEx:eval"
        }
    }, 
    "contexts": {
        "Context-1": {
            "enabled": true, 
            "num_users": 32
        }
    }, 
    "benchmarks": {
        "Jactl": {
            "aps_rate": 2000.0, 
            "scenario_actions": [
                {
                    "id": 1, 
                    "weight": 100
                }
            ], 
            "warmup_duration1": 30, 
            "warmup_duration2": 30, 
            "benchmark_duration": 30, 
            "benchmark_iterations": 3
        }, 
        "Groovy": {
            "aps_rate": 2000.0, 
            "scenario_actions": [
                {
                    "id": 2, 
                    "weight": 100
                }
            ], 
            "warmup_duration1": 30, 
            "warmup_duration2": 30, 
            "benchmark_duration": 30, 
            "benchmark_iterations": 3
        }, 
        "Jython": {
            "aps_rate": 2000.0, 
            "scenario_actions": [
                {
                    "id": 3, 
                    "weight": 100
                }
            ], 
            "warmup_duration1": 30, 
            "warmup_duration2": 30, 
            "benchmark_duration": 30, 
            "benchmark_iterations": 3
        }, 
        "All": {
            "aps_rate": 2000.0, 
            "scenario_actions": [
                {
                    "id": 1, 
                    "weight": 34
                }, 
                {
                    "id": 2, 
                    "weight": 33
                }, 
                {
                    "id": 3, 
                    "weight": 33
                }
            ], 
            "warmup_duration1": 30, 
            "warmup_duration2": 10, 
            "benchmark_duration": 30, 
            "benchmark_iterations": 3
        }
    }
}
----

== JVM System Properties

* java.vendor: Eclipse Adoptium
* java.version: 26.0.2.1
* java.runtime.version: 26.0.2.1+1
* os.name: Linux
* os.arch: amd64

== JVM Runtime Options

* Option 1: -Xmx2g
* Option 2: -Xms2g
